// // const jwt = require('jsonwebtoken');
// // const User = require('../models/User');

// // const JWT_SECRET = process.env.JWT_SECRET || 'your-super-secret-jwt-key-change-this-in-production';

// // const authenticateToken = async (req, res, next) => {
// //   try {
// //     // Get token from header
// //     const authHeader = req.headers['authorization'];
// //     const token = authHeader && authHeader.split(' ')[1]; // Bearer TOKEN

// //     if (!token) {
// //       return res.status(401).json({
// //         success: false,
// //         message: 'Access token is required'
// //       });
// //     }

// //     // Verify token
// //     const decoded = jwt.verify(token, JWT_SECRET);
    
// //     // Get user from token
// //     const user = await User.findById(decoded.userId).select('-password');
    
// //     if (!user) {
// //       return res.status(401).json({
// //         success: false,
// //         message: 'Invalid token - user not found'
// //       });
// //     }

// //     // Add user to request object
// //     req.user = user;
// //     next();

// //   } catch (error) {
// //     console.error('Auth middleware error:', error);
    
// //     if (error.name === 'JsonWebTokenError') {
// //       return res.status(401).json({
// //         success: false,
// //         message: 'Invalid token'
// //       });
// //     }
    
// //     if (error.name === 'TokenExpiredError') {
// //       return res.status(401).json({
// //         success: false,
// //         message: 'Token expired'
// //       });
// //     }

// //     return res.status(500).json({
// //       success: false,
// //       message: 'Internal server error'
// //     });
// //   }
// // };

// // module.exports = { authenticateToken };
// const { admin } = require('../services/firebaseAdmin');

// const authenticateToken = async (req, res, next) => {
//   try {
//     const authHeader = req.headers['authorization'];
//     const token = authHeader && authHeader.split(' ')[1]; // Bearer TOKEN

//     if (!token) {
//       return res.status(401).json({
//         success: false,
//         message: 'Access token is required'
//       });
//     }

//     if (!admin) {
//       return res.status(500).json({
//         success: false,
//         message: 'Authentication service unavailable'
//       });
//     }

//     // Verify Firebase ID Token
//     const decodedToken = await admin.auth().verifyIdToken(token);
    
//     // Attach user info to request
//     // decodedToken contains uid, email, picture, etc.
//     req.user = {
//       _id: decodedToken.uid, // Use Firebase UID as the primary ID
//       uid: decodedToken.uid,
//       email: decodedToken.email,
//       name: decodedToken.name || 'User',
//       picture: decodedToken.picture
//     };
    
//     next();

//   } catch (error) {
//     console.error('Auth middleware error:', error);
    
//     if (error.code === 'auth/id-token-expired') {
//       return res.status(401).json({
//         success: false,
//         message: 'Token expired'
//       });
//     }

//     return res.status(403).json({
//       success: false,
//       message: 'Invalid token'
//     });
//   }
// };

// module.exports = { authenticateToken };
// const jwt = require('jsonwebtoken');
// const { admin } = require('../services/firebaseAdmin');
// const User = require('../models/User');

// const authenticateToken = async (req, res, next) => {
//   try {
//     const authHeader = req.headers['authorization'];
//     const token = authHeader && authHeader.split(' ')[1]; // Bearer <token>

//     if (!token) {
//       return res.status(401).json({ success: false, message: 'Access token is required' });
//     }

//     // 1. Verify the token with Firebase Admin
//     // This ensures the token is valid and generated by Google
//     const decodedToken = await admin.auth().verifyIdToken(token);
//     const { uid, email } = decodedToken;

//     // 2. Find the user in MongoDB using the Firebase UID (or email)
//     // We assume your User model has a 'googleUid' or 'email' field
//     let user = await User.findOne({ 
//       $or: [{ googleUid: uid }, { email: email }] 
//     });

//     if (!user) {
//       // Optional: If user logs in via Firebase but isn't in Mongo yet, 
//       // you could create them here dynamically, or return 404.
//       // For now, we return error.
//       return res.status(404).json({ success: false, message: 'User account not found in database.' });
//     }

//     // 3. Attach the MONGODB User object to the request
//     // This allows routes to access req.user._id, req.user.isProUser, etc.
//     req.user = user; 
    
//     // Attach firebase info just in case
//     req.firebaseUser = decodedToken;

//     next();

//   } catch (error) {
//     console.error('Auth middleware error:', error);
//     if (error.code === 'auth/id-token-expired') {
//       return res.status(401).json({ success: false, message: 'Token expired' });
//     }
//     return res.status(403).json({ success: false, message: 'Invalid token' });
//   }
// };

// module.exports = { authenticateToken };
const jwt = require('jsonwebtoken');
const User = require('../models/User');

const authenticateToken = async (req, res, next) => {
  try {
    // 1. Get the token from the header
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1]; // Bearer <token>

    if (!token) {
      return res.status(401).json({ success: false, message: 'Access token is required' });
    }

    // 2. Verify the Custom JWT (Corrected Step)
    // We use jwt.verify instead of admin.auth().verifyIdToken
    // This matches the jwt.sign() used in your routes/auth.js
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'your-secret-key-here');

    // 3. Find the user in MongoDB
    // The payload from your generateToken function is { userId: ... }
    const user = await User.findById(decoded.userId);

    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found' });
    }

    // 4. Attach the user to the request
    req.user = user;
    
    next();

  } catch (error) {
    console.error('Auth middleware error:', error.message);
    
    if (error.name === 'TokenExpiredError') {
      return res.status(401).json({ success: false, message: 'Token expired' });
    }
    
    return res.status(403).json({ success: false, message: 'Invalid token' });
  }
};

module.exports = { authenticateToken };